OpenServer/domains/Lab/routes/web.php
<?php

use App\Http\Controllers\CompaniesController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ShowProfileController;
use App\Http\Controllers\HomeController;
use App\Models\Company;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/companies', [CompaniesController::class, 'index']);


Route::resource('companies', CompaniesController::class);

Route::get('/about', [HomeController::class, 'about']);

Route::get('/members', [HomeController::class, 'members']);

Route::get('/user/{name?}', [UserController::class, 'show']);

Route::get('/home', [HomeController::class, 'index']);


Route::get('/users', [UserController::class, 'list']);

Route::get('/show/{name}', [ShowProfileController::class, 'show']);


Route::get('/', function () {
    return view('welcome');
});

Route::get('/user/{id}', [ShowProfileController::class,'show']);






// Route::get('/search', function (Request $request) {
//     return $request->all();
// });

// Route::group(['prefix'=>'dashboard'], function(){
//     Route::get('/users', function(){
//         return 'Users dashboard';
//     });

//     Route::get('/statistic', function(){
//         return 'Statistic dashboard';
//     });
// });

// // Route::get('/search', function (Request $request) {
// //     $name = $request->get('name','Shaxzod');
// //     $age = $request->get('age',31);
// //     return $name.' ismli foydalanuvchi ' . $age. ' yoshda';
// // });

// Route::get('/{action}/{name?}', function ($action, $name=null) {
//     return $action.$name;
// });

// Route::get('/user/{name?}', function ($name=null) {
//     return 'Hello, user ' . $name;
// });

OpenServer/domains/Lab/app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['name','address','phone'];

    //table - companies nomi o'rniga boshqa nom bermooqchi bo'lsak kod quyidagicha:

        //protected $table = 'his_companies';

    //primary key o'rniga boshqa nom bermoqchi bo'lsak

        //protected $primaryKey = 'Company_id';

    // incrementingga zarurat bo'lmasa

        // public $incrementing = false;

    // timestamps ga zarurat bo'lmasa

        // public $timestamps = false;

    // default values

        // protected $attributes = [
        //     'active' => true
        // ];
}

OpenServer/domains/Lab/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

OpenServer/domains/Lab/app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SaveCompanyRequst;
use App\Models\Company;
use App\Rules\PhoneNumber;
use Illuminate\Http\Request;


class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::orderByDesc('created_at')->paginate(20);
        return view('companies.index',[
            'companies' => $companies 
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = new Company();
        return view('companies.create', [
            'company' => $company
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveCompanyRequst $request)
    {

       // dd($this->validatedData());

        Company::create($request->validated());

        return redirect()->route('companies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //$company = Company::findOrFail($company);

        return view('companies.show', [
            'company' => $company
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('companies.edit', [
            'company' => $company
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SaveCompanyRequst $request, Company $company)
    {

        $company->update($request->validated());

        return redirect()->route('companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()->route('companies.index');
    }
}

OpenServer/domains/Lab/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

OpenServer/domains/Lab/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('app');
    }

    public function members()
    {
        $members = [
            // 'Rasul Hamzatov',
            // 'Qosim To\'qayev',
            // 'Azamat Tursunov'
        ];
        return view('members', compact('members'));
    }

    public function about()
    {
        return view('about');
    }
}

OpenServer/domains/Lab/app/Http/Controllers/ShowProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ShowProfileController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

     public function show($name=null)
    {
        return view('show', [
            'username' => $name
        ]);
    }
    
    public function list() 
    {
        $users = [
            'Komil',
            'Halim',
            'Salim',
            'Qamar'
        ];

        return view('list', compact('users'));
    }



}

OpenServer/domains/Lab/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    public function show($name=null) {

        $plans = ['free', 'premium', 'gold'];

        return view('users.show', [
            'username' => $name,
            'plans' => $plans
        ]);
    }

    public function list() 
    {
        $users = [
            'Salim',
            'Halim',
            'Tolib',
            'Qobil'
        ];

        $plans = ['free', 'premium', 'gold'];

        return view('users.list', compact('users','plans'));
    }
}

OpenServer/domains/Lab/resources/views/about.blade.php
@extends('app')

@section('title', 'Bu about sahifasi')
@section('content')
    <h1>Hammaga assalomu alaykum bu korxona haqida ma'lumot beruvchi sahifa</h1>
@endsection

OpenServer/domains/Lab/resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Laravel 9 darslari</title>
</head>
<body>
    <div class="container">
        @yield('content')
    </div>
    
</body>
</html>

OpenServer/domains/Lab/resources/views/companies/create.blade.php
@extends('layouts.app')
@section('content')
    <h1 class="text-center p-3">Laboratoriya qo'shish</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form method="post" action="{{ route('companies.store') }}">
                @csrf
                @include('companies.form')
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </form>
        </div>
    </div>
    
@endsection

OpenServer/domains/Lab/resources/views/companies/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1 class="text-center p-3">Laboratoriya ma'lumotlarini o'zgartirish</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form method="post" action="{{ route('companies.update', ['company' => $company->id]) }}">
                @method('PUT')
                @csrf
                @include('companies.form')     
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </form>
        </div>
    </div>
    
@endsection

OpenServer/domains/Lab/resources/views/companies/form.blade.php
<div class="mb-3">
    <label for="name" class="form-label">Laboratoriya nomi</label>
    <input type="text" class="form-control" id="name" name="name" value="{{ old('name') ?? $company->name }}">
</div>
<div class="mb-3">
    <label for="address" class="form-label">Laboratoriya manzili</label>
    <input type="text" class="form-control" id="address" name="address" value="{{ old('address') ?? $company->address }}">
</div>
<div class="mb-3">
    <label for="phone" class="form-label">Laboratoriya telefon raqami</label>
    <input type="text" class="form-control" id="phone" name="phone" value="{{ old('phone') ?? $company->phone }}">
</div> 

OpenServer/domains/Lab/resources/views/companies/index.blade.php
@extends('layouts.app')
@section('content')
<h2 class="text-center">Bu laboratoriyalar ro'yxati</h2>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a href="{{ route('companies.create')}}"> <button class="btn btn-success" type="button">Laboratoriya qo'shish</button></a>
</div>
<br>
<table class="table table-bordered">
    <tdead>
        <tr>
            <th>T/R</th>
            <th>Laboratoriya nomi</th>
            <th>Laboratoriya manzili</th>
            <th>Laboratoriya raqami</th>
            <th>Tahrirlash</th>
        </tr>
    </tdead>
    <tbody>
        @foreach($companies as $company)
            <tr>
                <td>
                        
                {{ ($companies->currentpage()-1)*$companies->perpage() + ($loop->index+1) }}</td>
                <td><a href="{{ route('companies.show', ['company' => $company->id]) }} ">{{ $company->name}}</a></td>
                <td>{{ $company->address }}</td>
                <td>{{ $company->phone }}</td>
                <td>
                    <a href="{{ route('companies.edit', ['company' => $company->id]) }}" class="btn btn-info"><i class="bi bi-pencil-fill"></i></a>
                    <form action="{{route('companies.destroy', ['company'=> $company->id]) }}" method="post"> 
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i></button>
                    </form>
                    
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
{{ $companies->links() }}
@endsection

OpenServer/domains/Lab/resources/views/companies/show.blade.php
@extends('layouts.app')
@section('content')
    <h1 class="text-center p-3">Laboratoriya haqida ma'lumot</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="mb-3">
                <a href="{{ route('companies.index') }}">Ortga</a>
            </div>
            <table class="table table-bordered">
                <tr>
                    <td>Laboratoriya nomi</td>
                    <td>{{ $company->name }}</td>
                </tr>       
                <tr>
                    <td>Laboratoriya manzili</td>
                    <td>{{ $company->address }}</td>
                </tr>
                <tr>
                    <td>Laboratoriya telefoni</td>
                    <td>{{ $company->phone }}</td>
                </tr>
                <tr>
                    <td>Qo'shilgan vaqti</td>
                    <td>{{ $company->created_at }}</td>
                </tr>
            </table>
        </div>
    </div>
    
@endsection

OpenServer/domains/Lab/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

OpenServer/domains/Lab/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Laravel 9 darslari</title>
</head>
<body>
    <div class="contaner">
        @yield('content')
    </div>   
    
</body>
</html>

OpenServer/domains/Lab/resources/views/members.blade.php
@extends('app')

@section('title', 'Bu jamoa azolari sahifasi')

@section('content')

<h1>Bu members sahifasi</h1>
<ul>
    @foreach($members as $member)
    <li>{{ $member }} </li>
    @empty
        Hech qanday jamoa a'zosi mavjud emas.
    @endforelse
</ul>

@endsection

OpenServer/domains/Lab/resources/views/users/list.blade.php
<html>
    <body>
        <h2>Foydalanuvchilar ro'yxati</h2>
        <ul>
            @foreach($users as $user)
            <li>{{ $user }}</li>
            @endforeach
        </ul>
    </body>
</html>

OpenServer/domains/Lab/resources/views/users/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Bu show profile. Foydalanuvchining ismi {{ $username }, {$plans} }</h1>
</body>
</html>